apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  labels:
    {{- include "deis-workflow.labels" . | nindent 4 }}
data:
{{ (tpl (.Files.Glob "configs/nginx/*").AsConfig . ) | indent 2 }}

